#!/bin/bash

# Connect to the portal machine at UFRGS, copy experiments from my personal
# machine in the research group laboratory to the portal machine, and then
# to the computer from where I'm running this script.

user_portal='hbecker'
user_server='henrique'

server=$1
file_or_dir=${2%/}
# The copy of the files to the portal takes the '--delete' flag so any
# previous garbage in a folder with the same name (inside portal) will not be
# copied by the second rsync (from portal to the local machine).
ssh -oHostKeyAlgorithms=+ssh-rsa -T $user_portal@portal.inf.ufrgs.br <<-ENDSSH
  rsync -a --delete --progress "$user_server@$server:/home/$user_server/$file_or_dir" .
ENDSSH
# This copy does not take '--delete' to avoide deleting something of
# importance on the local machine. The files in portal (from previous
# transfers) are not regarded as important as files in the local machine.
rsync -a --progress -e "ssh -oHostKeyAlgorithms=+ssh-rsa" "$user_portal@portal.inf.ufrgs.br:/home/pos/$user_portal/`basename $file_or_dir`" .

